### ISSUE TITLE
Weird angular data binding syntax

### ISSUE THREAD

**Issue by DanielSank** [DanielSank/pong#9]
@maffoo [this](https://github.com/DanielSank/pong/commit/476de0d139b41bc1b61dc6669405e92e8f7dccf1#diff-129ecab9d370e6a798ec66de1debeb1fR11) is the weird stuff that seems "off" in Angular, IMHO.

**Comment by maffoo** [comment]
There are two levels of weirdness there. It's possible to do bindings without the strange attribute names, using `on-foo="bar"` instead of `(foo)="bar"`, or using `bindon-foo="bar"` instead of `[(foo)]="bar"` (see [here](https://angular.io/guide/template-syntax#binding-syntax-an-overview)). Then there's the usage of `ngModel` which seems to be something special in its own right. I don't know if one can replace the snippet you linked to with `bindon-ngModel` or if it somehow gets handled in a different way. This stuff feels "off" to my eyes as well.
